server:
  session-timeout: 60
  port: 8088
redis:
  hostName: localhost
  #password:
  port: 6379
  timeout: 10000
  maxWaitMillis: 1000
  testOnBorrow: true
  testWhileIdle: true
  maxIdle: 300
  minEvictableIdleTimeMillis: 300000
  timeBetweenEvictionRunsMillis: 30000
  maxTotal: 1000
  numTestsPerEvictionRun: 1024
  #哨兵模式根据名称自动选择master
  sentinel:
    master: mymaster
    nodes: 192.168.2.183:7000,192.168.2.183:7001,192.168.2.183:7002
cluster:
  nodes: 192.168.2.183:7000,192.168.2.183:7001,192.168.2.183:7002,192.168.2.183:7003,192.168.2.183:7004,192.168.2.183:7005
  max-redirects: 3
data:
  mongodb:
    uri: mongodb://admin:admin@127.0.0.1:27017,127.0.0.1:27017,127.0.0.1:27017
    database: PcWeb
dubbo:
      registry:
        address: zookeeper://127.0.0.1:2181
      application:
        name: consumer
      base-package: controller
